spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        generate_statistics: true
        #show_sql: true
        format_sql: true
        default_batch_fetch_size: 100 # 쿼리 in (?,?,?...) <?> 개수 (글로벌)

logging:
  level:
    #    org.hibernate: debug
    org.hibernate.stat: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace
